php artisan migrate-old-data:achievement-condition-list
php artisan migrate-old-data:categories
php artisan migrate-old-data:host
php artisan migrate-old-data:languages
php artisan migrate-old-data:pitch-template
php artisan migrate-old-data:project-industry
php artisan migrate-old-data:project-stages
php artisan migrate-old-data:project-status
php artisan migrate-old-data:project-type
php artisan migrate-old-data:project-verticals
php artisan migrate-old-data:ranks
php artisan migrate-old-data:social-link
php artisan migrate-old-data:tags
php artisan migrate-old-data:tag-groups
php artisan migrate-old-data:skills
php artisan migrate-old-data:skill-stacks
php artisan migrate-old-data:skill-groups
php artisan migrate-old-data:project-pitchs
php artisan migrate-old-data:project-tasks
php artisan migrate-old-data:users
php artisan db:seed --class=ChannelApiOrganizationSeeder
php artisan migrate-old-data:organizations
php artisan migrate-old-data:role
php artisan migrate-old-data:labs
php artisan migrate-old-data:lab-program
php artisan migrate-old-data:challenge
php artisan migrate-old-data:challenge-path
php artisan migrate-old-data:resource-modules
php artisan migrate-old-data:resource-collection
php artisan migrate-old-data:resource-groups
php artisan migrate-old-data:users-achievement
php artisan migrate-old-data:jobs-titles
php artisan register:go1-webhook
php artisan migrate-old-data:component-association-migration
php artisan migrate-old-data:users-skills
php artisan migrate-old-data:users-personal
php artisan migrate-old-data:users-patent
php artisan migrate-old-data:users-experiences
php artisan migrate-old-data:users-education
php artisan migrate-old-data:users-certificate
php artisan migrate-old-data:users-address
php artisan migrate-old-data:users-friends
php artisan migrate-old-data:users-tags
php artisan migrate-old-data:users-setting
php artisan migrate-old-data:project
php artisan migrate-old-data:discussion
php artisan migrate-old-data:project-history
php artisan migrate:feed-chargebee-data-to-data-base
